# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Setup common testing tools
description: Install bats and python-yq
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "24"
    - run: npm install -g bats@${BATS_VERSION}
      shell: bash
      env:
        BATS_VERSION: "1.8.2"
    - run: bats -v
      shell: bash
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.14"
    - run: pip install yq
      shell: bash
permissions:
  contents: read
