# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: openbao
version: 0.29.0
appVersion: v2.6.1
kubeVersion: ">= 1.30.0-0"
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://raw.githubusercontent.com/openbao/artwork/refs/heads/main/color/openbao-color.svg
keywords:
  [
    "vault",
    "openbao",
    "security",
    "encryption",
    "secrets",
    "management",
    "automation",
    "infrastructure",
  ]
sources:
  - https://github.com/openbao/openbao-helm
annotations:
  charts.openshift.io/name: OpenBao
  charts.openshift.io/provider: OpenBao
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: fixed
      description: |
       fix(openshift): update readinessProbe to support horizontal scalability
    - kind: fixed
      description: |
        fix: Add global imagePullSecrets to Snapshot CronJob
    - kind: fixed
      description: |
        fix(openshift): use non certified quay.io ubi container image
    - kind: fixed
      description: |
        fix(chart): preserve custom BackendTLSPolicy validation hostname
    - kind: fixed
      description: |
        fix(httpRoute): template timeouts in rule
    - kind: fixed
      description: |
        fix: allow using custom Secret keys for Snapshot Agent S3 credentials.
    - kind: changed
      description: |
        feat: apply server.statefulset.securityContext on helm test pod
    - kind: changed
      description: |
        feat: Support bearerTokenFile for ServiceMonitor
    - kind: changed
      description: |
        chore: update openbao-snapshot-agent to version 0.4.0 and add additional configuration
    - kind: changed
      description: |
        chore: update to openbao-csi-provider 2.0.3
    - kind: changed
      description: |
        chore(chart): remove obsolete Kubernetes API and version compatibility checks

maintainers:
  - name: OpenBao
    email: openbao-security@lists.openssf.org
    url: https://openbao.org
