name: OCM
on: [workflow_call]

jobs:
  ocm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup ocm-cli
        run: |
          VERSION="0.26.0"
          ARCHIVE_FILE="ocm-${VERSION}-linux-amd64.tar.gz"
          URL="https://github.com/open-component-model/ocm/releases/download/v${VERSION}/$ARCHIVE_FILE"

          echo "Installing ocm-cli version v${VERSION} from ${URL}"

          curl -LsS -o ocm-cli.tgz "$URL"
          tar --overwrite -xvzf ocm-cli.tgz -C /usr/local/bin
          chmod a+x /usr/local/bin/ocm

      - name: Write .ocmconfig
        run: |
          cat <<EOF > $HOME/.ocmconfig
          type: generic.config.ocm.software/v1
          configurations:
            - type: credentials.config.ocm.software
              consumers:
                - identity:
                    type: OCIRegistry
                    scheme: https
                    hostname: ghcr.io
                  credentials:
                    - type: Credentials
                      properties:
                        username: ${{ github.actor }}
                        password: ${{ secrets.GITHUB_TOKEN }}
          EOF

      - name: Create Helm Chart archive
        run: |
          helm package charts/openbao

      - name: Create OCM component archive
        run: |
          OPENBAO_REGISTRY=$(yq '.server.image.registry' ./charts/openbao/values.yaml)
          OPENBAO_VERSION=$(yq '.appVersion | sub("v", "")' ./charts/openbao/Chart.yaml)
          CHART_VERSION=$(yq '.version' ./charts/openbao/Chart.yaml)
          OPENBAO_CSI_VERSION=$(yq '.csi.image.tag' ./charts/openbao/values.yaml)
          INJECTOR_REGISTRY=$(yq '.injector.image.registry' ./charts/openbao/values.yaml)
          INJECTOR_REPOSITORY=$(yq '.injector.image.repository' ./charts/openbao/values.yaml)
          INJECTOR_VERSION=$(yq '.injector.image.tag' ./charts/openbao/values.yaml)

          echo "Building OCM artifact for ${CHART_VERSION}"

          ocm add componentversions --create --templater=go --file=ocm/transport.ctf ocm/component-constructor.yaml -- \
                            COMPONENT_NAME="openbao.org/openbao" \
                            PROVIDER="openbao" \
                            OPENBAO_REGISTRY=${OPENBAO_REGISTRY} \
                            OPENBAO_VERSION=${OPENBAO_VERSION} \
                            OPENBAO_CHART_VERSION=${CHART_VERSION} \
                            OPENBAO_CSI_VERSION=${OPENBAO_CSI_VERSION} \
                            INJECTOR_REGISTRY=${INJECTOR_REGISTRY} \
                            INJECTOR_REPOSITORY=${INJECTOR_REPOSITORY} \
                            INJECTOR_VERSION=${INJECTOR_VERSION}

      - name: Push OCM artifact to OCI
        run: |
          OCI_REGISTRY="ghcr.io/openbao"
          echo "Pushing to ${OCI_REGISTRY} as user '${{ github.actor }}'"
          ocm transfer ctf ./ocm/transport.ctf OCIRegistry::${OCI_REGISTRY}
