name: Tests
on: [push, workflow_dispatch, pull_request]
jobs:
  bats-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-test-tools
      - run: bats --tap --timing ./test/unit
  chart-verifier:
    runs-on: ubuntu-latest
    env:
      CHART_VERIFIER_VERSION: "1.13.9"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup test tools
        uses: ./.github/actions/setup-test-tools
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22.5"
      - run: go install "github.com/redhat-certification/chart-verifier@${CHART_VERIFIER_VERSION}"
      - run: bats --tap --timing ./test/chart
permissions:
  contents: read
